using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Unicode
    {
        /// <summary>
        /// fa-rabbit unicode value ("\uf708").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid (Pro), Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/rabbit
        /// </summary>
        public const string Rabbit = "\uf708";
    }

    /// <summary>
    /// The Css values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Css
    {
        /// <summary>
        /// Rabbit unicode value ("fa-rabbit").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid (Pro), Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/rabbit
        /// </summary>
        public const string Rabbit = "fa-rabbit";
    }

    /// <summary>
    /// The Icon names for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Icon
    {
        /// <summary>
        /// fa-rabbit unicode value ("\uf708").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid (Pro), Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/rabbit
        /// </summary>
        public const string Rabbit = "Rabbit";
    }
}