using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Unicode
    {
        /// <summary>
        /// fa-stop-circle unicode value ("\uf28d").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/stop-circle
        /// </summary>
        public const string StopCircle = "\uf28d";
    }

    /// <summary>
    /// The Css values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Css
    {
        /// <summary>
        /// StopCircle unicode value ("fa-stop-circle").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/stop-circle
        /// </summary>
        public const string StopCircle = "fa-stop-circle";
    }

    /// <summary>
    /// The Icon names for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Icon
    {
        /// <summary>
        /// fa-stop-circle unicode value ("\uf28d").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/stop-circle
        /// </summary>
        public const string StopCircle = "StopCircle";
    }
}