using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Unicode
    {
        /// <summary>
        /// fa-ember unicode value ("\uf423").
        /// <para/>
        /// This icon supports the following styles: Brands
        /// <para/>
        /// See https://fontawesome.com/icons/ember
        /// </summary>
        public const string Ember = "\uf423";
    }

    /// <summary>
    /// The Css values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Css
    {
        /// <summary>
        /// Ember unicode value ("fa-ember").
        /// <para/>
        /// This icon supports the following styles: Brands
        /// <para/>
        /// See https://fontawesome.com/icons/ember
        /// </summary>
        public const string Ember = "fa-ember";
    }

    /// <summary>
    /// The Icon names for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Icon
    {
        /// <summary>
        /// fa-ember unicode value ("\uf423").
        /// <para/>
        /// This icon supports the following styles: Brands
        /// <para/>
        /// See https://fontawesome.com/icons/ember
        /// </summary>
        public const string Ember = "Ember";
    }
}