using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Unicode
    {
        /// <summary>
        /// fa-user-plus unicode value ("\uf234").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/user-plus
        /// </summary>
        public const string UserPlus = "\uf234";
    }

    /// <summary>
    /// The Css values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Css
    {
        /// <summary>
        /// UserPlus unicode value ("fa-user-plus").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/user-plus
        /// </summary>
        public const string UserPlus = "fa-user-plus";
    }

    /// <summary>
    /// The Icon names for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Icon
    {
        /// <summary>
        /// fa-user-plus unicode value ("\uf234").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/user-plus
        /// </summary>
        public const string UserPlus = "UserPlus";
    }
}