using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Unicode
    {
        /// <summary>
        /// fa-list unicode value ("\uf03a").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/list
        /// </summary>
        public const string List = "\uf03a";
    }

    /// <summary>
    /// The Css values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Css
    {
        /// <summary>
        /// List unicode value ("fa-list").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/list
        /// </summary>
        public const string List = "fa-list";
    }

    /// <summary>
    /// The Icon names for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Icon
    {
        /// <summary>
        /// fa-list unicode value ("\uf03a").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/list
        /// </summary>
        public const string List = "List";
    }
}