using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Unicode
    {
        /// <summary>
        /// fa-repeat unicode value ("\uf363").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid (Pro), Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/repeat
        /// </summary>
        public const string Repeat = "\uf363";
    }

    /// <summary>
    /// The Css values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Css
    {
        /// <summary>
        /// Repeat unicode value ("fa-repeat").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid (Pro), Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/repeat
        /// </summary>
        public const string Repeat = "fa-repeat";
    }

    /// <summary>
    /// The Icon names for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Icon
    {
        /// <summary>
        /// fa-repeat unicode value ("\uf363").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid (Pro), Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/repeat
        /// </summary>
        public const string Repeat = "Repeat";
    }
}