using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Unicode
    {
        /// <summary>
        /// fa-flag unicode value ("\uf024").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/flag
        /// </summary>
        public const string Flag = "\uf024";
    }

    /// <summary>
    /// The Css values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Css
    {
        /// <summary>
        /// Flag unicode value ("fa-flag").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/flag
        /// </summary>
        public const string Flag = "fa-flag";
    }

    /// <summary>
    /// The Icon names for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Icon
    {
        /// <summary>
        /// fa-flag unicode value ("\uf024").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/flag
        /// </summary>
        public const string Flag = "Flag";
    }
}