using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Unicode
    {
        /// <summary>
        /// fa-chair unicode value ("\uf6c0").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/chair
        /// </summary>
        public const string Chair = "\uf6c0";
    }

    /// <summary>
    /// The Css values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Css
    {
        /// <summary>
        /// Chair unicode value ("fa-chair").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/chair
        /// </summary>
        public const string Chair = "fa-chair";
    }

    /// <summary>
    /// The Icon names for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Icon
    {
        /// <summary>
        /// fa-chair unicode value ("\uf6c0").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/chair
        /// </summary>
        public const string Chair = "Chair";
    }
}