using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Unicode
    {
        /// <summary>
        /// fa-google-plus-square unicode value ("\uf0d4").
        /// <para/>
        /// This icon supports the following styles: Brands
        /// <para/>
        /// See https://fontawesome.com/icons/google-plus-square
        /// </summary>
        public const string GooglePlusSquare = "\uf0d4";
    }

    /// <summary>
    /// The Css values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Css
    {
        /// <summary>
        /// GooglePlusSquare unicode value ("fa-google-plus-square").
        /// <para/>
        /// This icon supports the following styles: Brands
        /// <para/>
        /// See https://fontawesome.com/icons/google-plus-square
        /// </summary>
        public const string GooglePlusSquare = "fa-google-plus-square";
    }

    /// <summary>
    /// The Icon names for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Icon
    {
        /// <summary>
        /// fa-google-plus-square unicode value ("\uf0d4").
        /// <para/>
        /// This icon supports the following styles: Brands
        /// <para/>
        /// See https://fontawesome.com/icons/google-plus-square
        /// </summary>
        public const string GooglePlusSquare = "GooglePlusSquare";
    }
}