using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Unicode
    {
        /// <summary>
        /// fa-sort-shapes-up unicode value ("\uf88a").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid (Pro), Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/sort-shapes-up
        /// </summary>
        public const string SortShapesUp = "\uf88a";
    }

    /// <summary>
    /// The Css values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Css
    {
        /// <summary>
        /// SortShapesUp unicode value ("fa-sort-shapes-up").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid (Pro), Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/sort-shapes-up
        /// </summary>
        public const string SortShapesUp = "fa-sort-shapes-up";
    }

    /// <summary>
    /// The Icon names for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Icon
    {
        /// <summary>
        /// fa-sort-shapes-up unicode value ("\uf88a").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid (Pro), Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/sort-shapes-up
        /// </summary>
        public const string SortShapesUp = "SortShapesUp";
    }
}