using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Unicode
    {
        /// <summary>
        /// fa-hand-spock unicode value ("\uf259").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/hand-spock
        /// </summary>
        public const string HandSpock = "\uf259";
    }

    /// <summary>
    /// The Css values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Css
    {
        /// <summary>
        /// HandSpock unicode value ("fa-hand-spock").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/hand-spock
        /// </summary>
        public const string HandSpock = "fa-hand-spock";
    }

    /// <summary>
    /// The Icon names for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Icon
    {
        /// <summary>
        /// fa-hand-spock unicode value ("\uf259").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/hand-spock
        /// </summary>
        public const string HandSpock = "HandSpock";
    }
}