using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Unicode
    {
        /// <summary>
        /// fa-theater-masks unicode value ("\uf630").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/theater-masks
        /// </summary>
        public const string TheaterMasks = "\uf630";
    }

    /// <summary>
    /// The Css values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Css
    {
        /// <summary>
        /// TheaterMasks unicode value ("fa-theater-masks").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/theater-masks
        /// </summary>
        public const string TheaterMasks = "fa-theater-masks";
    }

    /// <summary>
    /// The Icon names for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/michaelswells/fa2cs a modified fork from https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class Icon
    {
        /// <summary>
        /// fa-theater-masks unicode value ("\uf630").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/theater-masks
        /// </summary>
        public const string TheaterMasks = "TheaterMasks";
    }
}